/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fbase

import java.io.*
import java.net.*
import fbase.server.*

fun testdayon(socket: Socket, reader: BufferedReader, writer: BufferedWriter){
    reader.lines().forEach{
        i -> println(i)
    }
}

fun main() {
    runFBaseServer(8082, ::testdayon)

    while(true){}

}
